name: 📚 Documenation
description: Use this form if you found an issue or have a suggestion regarding the **documentation** for the [AI on the edge device](https://github.com/jomjol/AI-on-the-edge-device) project.
labels: doc
body:

  - type: markdown
    attributes:
      value: |
        Thank you for taking your time to improve the documentation for the [AI on the edge device](https://github.com/jomjol/AI-on-the-edge-device) project.

        Du darfst gerne auch in Deutsch schreiben!

  - type: textarea
    validations:
      required: true
    attributes:
      label: The Problem/Improvement
      description: A clear and concise description of what the issue is.
